import 'dart:convert';
import 'dart:typed_data';

import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../config/device_contract.dart';
import '../models/calibration_log_entry.dart';

/// Builds a one-page certificate from the JSON response retained with a
/// calibration-history entry. Missing firmware fields deliberately remain N/A.
Future<Uint8List> generateCalibrationCertificatePdf({
  required CalibrationLogEntry record,
  required String nodeRole,
  required String signerName,
  required Uint8List signaturePng,
  DateTime? signedAt,
}) async {
  final values = _certificateValues(record.value);
  final calibratedAt = DeviceContract.deviceTimestamp(record.timestamp);
  final dateSigned = DeviceContract.deviceTimestamp(signedAt ?? DateTime.now());
  final document = pw.Document();

  document.addPage(
    pw.Page(
      pageFormat: PdfPageFormat.a4,
      margin: const pw.EdgeInsets.all(36),
      build: (context) => pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.stretch,
        children: [
          pw.Text(
            'Universal Battery Monitor - Calibration Certificate',
            style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold),
          ),
          pw.SizedBox(height: 16),
          _detail('Device Serial Number', record.deviceId),
          _detail('Node / Role', nodeRole),
          _detail('Calibration Date & Time', _humanDate(calibratedAt)),
          pw.SizedBox(height: 18),
          pw.Table(
            border: pw.TableBorder.all(color: PdfColors.grey500),
            columnWidths: const {
              0: pw.FlexColumnWidth(3),
              1: pw.FlexColumnWidth(2),
            },
            children: [
              _tableRow('Measurement', 'Voltage', header: true),
              _tableRow('True (Reference) Voltage', _voltage(values.reference)),
              _tableRow('Observed/Detected Voltage (before calibration)', _voltage(values.observed)),
              _tableRow('Corrected Voltage (after calibration)', _voltage(values.corrected)),
            ],
          ),
          pw.SizedBox(height: 8),
          pw.Text(
            'Calibration factor: ${values.factor == null ? 'N/A' : values.factor!.toStringAsFixed(3)}',
            style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey700),
          ),
          pw.Spacer(),
          pw.Divider(),
          pw.Text('Signed by', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
          pw.SizedBox(height: 4),
          pw.Text(signerName),
          pw.SizedBox(height: 4),
          pw.Container(
            height: 62,
            alignment: pw.Alignment.centerLeft,
            child: pw.Image(pw.MemoryImage(signaturePng), fit: pw.BoxFit.contain),
          ),
          _detail('Date signed', _humanDate(dateSigned)),
          pw.SizedBox(height: 12),
          pw.Center(
            child: pw.Text(
              'Digitally generated by ULink Programmer',
              style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey700),
            ),
          ),
        ],
      ),
    ),
  );
  return document.save();
}

pw.Widget _detail(String label, String value) => pw.Padding(
  padding: const pw.EdgeInsets.only(bottom: 4),
  child: pw.RichText(
    text: pw.TextSpan(
      children: [
        pw.TextSpan(text: '$label: ', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
        pw.TextSpan(text: value),
      ],
    ),
  ),
);

pw.TableRow _tableRow(String label, String value, {bool header = false}) => pw.TableRow(
  decoration: header ? const pw.BoxDecoration(color: PdfColors.grey300) : null,
  children: [
    pw.Padding(
      padding: const pw.EdgeInsets.all(7),
      child: pw.Text(label, style: header ? pw.TextStyle(fontWeight: pw.FontWeight.bold) : null),
    ),
    pw.Padding(
      padding: const pw.EdgeInsets.all(7),
      child: pw.Text(value, style: header ? pw.TextStyle(fontWeight: pw.FontWeight.bold) : null),
    ),
  ],
);

String _voltage(double? value) => value == null ? 'N/A' : '${value.toStringAsFixed(3)} V';

String _humanDate(String iso) {
  final value = DateTime.tryParse(iso);
  if (value == null) return iso;
  const months = [
    'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
    'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec',
  ];
  final hour = value.hour % 12 == 0 ? 12 : value.hour % 12;
  final period = value.hour >= 12 ? 'PM' : 'AM';
  final zone = value.timeZoneName.isEmpty ? DeviceContract.deviceTimestamp(value).substring(19) : value.timeZoneName;
  return '${value.day.toString().padLeft(2, '0')} ${months[value.month - 1]} ${value.year}, '
      '${hour.toString().padLeft(2, '0')}:${value.minute.toString().padLeft(2, '0')} $period $zone';
}

_CertificateValues _certificateValues(String? raw) {
  if (raw == null) return const _CertificateValues();
  try {
    final decoded = jsonDecode(raw);
    if (decoded is! Map) return const _CertificateValues();
    double? value(List<String> keys) {
      for (final key in keys) {
        final candidate = decoded[key];
        if (candidate is num) return candidate.toDouble();
        final parsed = double.tryParse(candidate?.toString() ?? '');
        if (parsed != null) return parsed;
      }
      return null;
    }

    final reference = value(const ['true_volt', 'true_voltage', 'volt_true_ref']);
    final observed = value(const ['detected_volt', 'detected_voltage', 'detectedVoltage']);
    final factor = value(const ['volt_factor', 'voltage_factor']);
    final corrected = value(const ['calibrated_volt', 'calibrated_voltage', 'voltage', 'volt']) ??
        (observed != null && factor != null ? observed * factor : null);
    return _CertificateValues(reference: reference, observed: observed, corrected: corrected, factor: factor);
  } on FormatException {
    return const _CertificateValues();
  }
}

class _CertificateValues {
  const _CertificateValues({this.reference, this.observed, this.corrected, this.factor});
  final double? reference;
  final double? observed;
  final double? corrected;
  final double? factor;
}
