import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../config/device_contract.dart';
import '../providers/connection_controller.dart';
import '../services/device_connection.dart' as device;
import '../widgets/connection_status_pill.dart';

class CalibrationScreen extends StatefulWidget { const CalibrationScreen({super.key}); @override State<CalibrationScreen> createState() => _CalibrationScreenState(); }
class _CalibrationScreenState extends State<CalibrationScreen> {
  final Set<String> _busy = {}; Map<String, dynamic>? _lastCalibration;
  Future<void> _run(String key, String command) async { setState(() => _busy.add(key)); try { final response = await context.read<ConnectionController>().command(command, logKey: key); if (!mounted) return; final decoded = _json(response); if (decoded != null) setState(() => _lastCalibration = decoded); _message(response, error: response.startsWith('ERROR:')); if (command == 'GET_CAL' || command.startsWith('RESET_')) await context.read<ConnectionController>().refreshCalibrationStatus(); } catch (e) { if (mounted) _message(_clean(e), error: true); } finally { if (mounted) setState(() => _busy.remove(key)); } }
  Future<void> _reference(bool temp) async { final v = await _ask('True ${temp ? 'temperature' : 'voltage'} reference'); if (v != null) await _run(temp ? 'temp' : 'volt', '${temp ? 'CAL_TEMP' : 'CAL_VOLT'}:$v'); }
  Future<String?> _ask(String title, {String? hint, bool allowEmpty = false}) async { final c = TextEditingController(); final r = await showDialog<String>(context: context, builder: (x) => AlertDialog(title: Text(title), content: TextField(controller: c, autofocus: true, keyboardType: const TextInputType.numberWithOptions(decimal: true, signed: true), decoration: InputDecoration(hintText: hint, border: const OutlineInputBorder())), actions: [TextButton(onPressed: () => Navigator.pop(x), child: const Text('Cancel')), FilledButton(onPressed: () { final v = c.text.trim(); if (v.isEmpty && !allowEmpty) return; Navigator.pop(x, v); }, child: const Text('Continue'))])); c.dispose(); return r; }
  Future<void> _serial() async { final current = await context.read<ConnectionController>().command('GET_SN', logKey: 'serial'); if (!mounted) return; final v = await _ask('Serial number', hint: 'Current: $current'); if (v != null) { if (!DeviceContract.serialPattern.hasMatch(v)) { _message('Serial must use the BATTERY-... format.', error: true); return; } await _run('serial', 'SET_SN:$v'); } }
  Future<void> _clock() async { final v = await _ask('Clock', hint: 'Blank reads; ISO-8601 sets.', allowEmpty: true); if (v != null) await _run('clock', v.isEmpty ? 'GET_TIME' : 'SET_TIME:$v'); }
  Future<void> _role() async { final current = await context.read<ConnectionController>().command('GET_ROLE', logKey: 'role'); if (!mounted) return; final choice = await showDialog<String>(context: context, builder: (x) => AlertDialog(title: const Text('Node role'), content: Text(current), actions: [TextButton(onPressed: () => Navigator.pop(x), child: const Text('Cancel')), TextButton(onPressed: () => Navigator.pop(x, 'MAKE_AVAILABLE'), child: const Text('Make available')), FilledButton(onPressed: () => Navigator.pop(x, 'MAKE_MASTER'), child: const Text('Make master'))])); if (choice != null) await _run('role', choice); }
  void _message(String s, {bool error = false}) => ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text(s.trim()), backgroundColor: error ? Theme.of(context).colorScheme.error : null));
  String _clean(Object e) => e.toString().replaceFirst(RegExp(r'^(StateError|Exception):\s*'), '');
  Map<String, dynamic>? _json(String s) { try { final v = jsonDecode(s); return v is Map ? Map<String, dynamic>.from(v) : null; } on FormatException { return null; } }
  @override Widget build(BuildContext context) { final c = context.watch<ConnectionController>(); final d = c.descriptor; if (d == null) return const Scaffold(body: Center(child: Text('No device connected.'))); final connected = c.connectionState == device.ConnectionState.connected; return DefaultTabController(length: 2, child: Scaffold(appBar: AppBar(title: Text(d.deviceId), actions: [Center(child: ConnectionStatusPill(state: c.connectionState)), IconButton(onPressed: () async { await c.disconnect(); if (context.mounted) Navigator.pop(context); }, icon: const Icon(Icons.link_off))], bottom: const TabBar(tabs: [Tab(icon: Icon(Icons.monitor_heart), text: 'Live'), Tab(icon: Icon(Icons.tune), text: 'Calibration')])), body: TabBarView(children: [_live(c), _actions(connected, c)]))); }
  Widget _live(ConnectionController c) => ListView(padding: const EdgeInsets.all(16), children: [Text('Live devices', style: Theme.of(context).textTheme.titleLarge), const Text('Updates arrive automatically every ~5 seconds. Master nodes can forward slave readings; each serial is separate.'), const SizedBox(height: 12), if (c.liveDevices.isEmpty) const Card(child: Padding(padding: EdgeInsets.all(16), child: Text('Waiting for live data…'))), ...c.liveDevices.map((r) => Card(child: ListTile(title: Text(r['serial']?.toString() ?? 'Unknown serial'), subtitle: Text('Temperature: ${r['temperature'] ?? '—'}\nVoltage: ${r['voltage'] ?? '—'}\nDatetime: ${r['datetime'] ?? 'UNSYNCED'}')))), _status(c.calibrationStatus)]);
  Widget _actions(bool connected, ConnectionController c) { final a = <_Action>[_Action('Calibrate Temperature', Icons.thermostat, () => _reference(true)), _Action('Calibrate Voltage', Icons.bolt, () => _reference(false)), _Action('View Calibration Status', Icons.fact_check, () => _run('status', 'GET_CAL')), _Action('Reset Temperature Calibration', Icons.restart_alt, () => _run('resetTemp', 'RESET_TEMP_CAL')), _Action('Reset Voltage Calibration', Icons.restart_alt, () => _run('resetVolt', 'RESET_VOLT_CAL')), _Action('Reset All Calibration', Icons.delete_sweep, () => _run('resetAll', 'RESET_CAL')), _Action('Serial Number', Icons.tag, _serial), _Action('Role', Icons.account_tree, _role), _Action('Clock', Icons.schedule, _clock)]; return ListView(padding: const EdgeInsets.all(16), children: [if (_lastCalibration != null) Card(child: Padding(padding: const EdgeInsets.all(12), child: Text('Last calibration response\n${const JsonEncoder.withIndent('  ').convert(_lastCalibration)}'))), const Text('Detected values are only available immediately after calibration; firmware does not push raw readings continuously.'), const SizedBox(height: 8), ...a.map((v) => Card(child: ListTile(leading: Icon(v.icon), title: Text(v.title), trailing: _busy.contains(v.title) ? const CircularProgressIndicator() : const Icon(Icons.chevron_right), onTap: connected ? v.run : null)))]); }
  Widget _status(Map<String, dynamic>? s) => Card(child: Padding(padding: const EdgeInsets.all(16), child: s == null ? const Text('Calibration status unavailable.') : Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text('Calibration status', style: Theme.of(context).textTheme.titleMedium), Text('Temperature: factor ${s['temp_factor']}, true ref ${s['temp_true_ref']}, calibrated ${s['temp_calibrated']}'), Text('Voltage: factor ${s['volt_factor']}, true ref ${s['volt_true_ref']}, calibrated ${s['volt_calibrated']}')] )));
}
class _Action { const _Action(this.title, this.icon, this.run); final String title; final IconData icon; final VoidCallback run; }
